### ISSUE TITLE
Syndicate-Qt quit unexpectedly

### ISSUE THREAD

**Issue by rippaio** [SyndicateLtd/SyndicateQT#1]
The app fails to load on MacOS

Process:               Syndicate-Qt [70982]
Path:                  /Applications/Syndicate-Qt.app/Contents/MacOS/Syndicate-Qt
Identifier:            co.Syndicate.Syndicate-Qt
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Syndicate-Qt [70982]
User ID:               1967427395

Date/Time:             2017-10-23 12:42:20.323 -0700
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        70A08393-C523-513F-FF30-C6622FA3C5CD

Time Awake Since Boot: 11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libgmp.10.dylib               	0x0000000101f2309b __gmpn_set_str + 315
1   co.Syndicate.Syndicate-Qt     	0x0000000101541fda secp256k1_ecdsa_verify + 682
2   co.Syndicate.Syndicate-Qt     	0x00000001010d129e CPubKey::Verify(uint256 const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) const + 174
3   co.Syndicate.Syndicate-Qt     	0x00000001010d01d3 CKey::VerifyPubKey(CPubKey const&) const + 387
4   co.Syndicate.Syndicate-Qt     	0x00000001010d0b66 ECC_InitSanityCheck() + 134
5   co.Syndicate.Syndicate-Qt     	0x000000010116198e InitSanityCheck() + 30
6   co.Syndicate.Syndicate-Qt     	0x0000000101162e78 AppInit2(boost::thread_group&) + 5032
7   co.Syndicate.Syndicate-Qt     	0x0000000101012d23 main + 4275
8   libdyld.dylib

**Comment by ncnf** [comment]
My Wallet on windows 1.9.1QT closes about 30 seconds after unlocking.


Help?

**Comment by neilkuumar** [comment]
any update on the macOS issue?

**Comment by lvilar** [comment]
Fixed in v1.9.9
