### ISSUE TITLE
Start-up warning whe using Old wallet.dat with the version 2.0.0.0.* dirty

### ISSUE THREAD

**Issue by marko56** [SyndicateLtd/SyndicateQT#16]
I installed the new version.
And copied the old wallet dat.
It seems everything is OK. However, at start it constantly reports warnig (and it starts much slower than with the empty wallet.dat) - see the attached file
![synx](https://user-images.githubusercontent.com/35567667/39967801-c8b546da-56b1-11e8-8d91-52e795eee567.png)

How to get read of the warning?

thanks

**Comment by lvilar** [comment]
This in normal behaviour, please use import private key option on new version of the wallet.dat to suppress the warning.

Regards,
Luka

**Comment by marko56** [comment]
Through the console I dumped the private key and tried to import it. However "it was already in the wallet".

Finally I got rid of the warning with:  "Tolls / Wallet Repair / Salvage wallet"
