### ISSUE TITLE
Make in Unix fails

### ISSUE THREAD

**Issue by kwiksand** [SyndicateLtd/SyndicateQT#2]
Old wallet built fine but this one failed on obj/alert.o errors, any ideas?

`g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wunused-function -Wunused-variable -fpermissive -Wconversion-null -g -DBOOST_SPIRIT_THREADSAFE -I/home/syndicate/syndicated/src -I/home/syndicate/syndicated/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -DENABLE_WALLET -I/home/syndicate/syndicated/src/secp256k1/include -I/home/syndicate/syndicated/src/leveldb/include -I/home/syndicate/syndicated/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
alert.cpp:257:1: fatal error: opening dependency file obj/alert.d: No such file or directory
 }
 ^
compilation terminated.
makefile.unix:217: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1`

**Comment by kwiksand** [comment]
(This is from following the standard build instructions in doc/build-unix.md - https://github.com/SyndicateLtd/SyndicateQT/blob/master/doc/build-unix.md)

**Comment by crypto5am** [comment]
Please create the folders `src/obj`, `src/obj/crypto`, `src/obj/support`. Although this issue should be fixed automatically if you download the commit.
