### ISSUE TITLE
Build QT in windows.

### ISSUE THREAD

**Issue by ctphu** [SyndicateLtd/SyndicateQT#3]
I make change this makefile.mingw

BOOST_SUFFIX?=-mgw49-mt-1_57

INCLUDEPATHS= \
 -I"$(CURDIR)" \
 -I"C:/dev/coindeps32" \
 -I"C:/dev/coindeps32/boost_1_57_0" \
 -I"C:/dev/coindeps32/db-4.8.30.NC/include" \
 -I"C:/dev/coindeps32/db-4.8.30.NC/build_unix" \
 -I"C:/dev/coindeps32/openssl-1.0.1p/include" \
 -I"C:/dev/coindeps32/secp256k1/include" \
 -I"C:/dev/coindeps32/miniupnpc" \
 -I"C:/dev/coindeps32/gmp-6.0.0"

LIBPATHS= \
 -L"$(CURDIR)/leveldb" \
 -L"C:/dev/coindeps32/boost_1_57_0/lib" \
 -L"C:/dev/coindeps32/db-4.8.30.NC/lib" \
 -L"C:/dev/coindeps32/openssl-1.0.1p" \
 -L"C:/dev/coindeps32/secp256k1/.lib" \
 -L"C:/dev/coindeps32/miniupnpc" \
 -L"C:/dev/coindeps32/gmp-6.0.0/.lib"

And when i run:
mingw32-make -f makefile.mingw
and i have this error:

C:/MinGW/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lboost_system-mgw49-mt-1_57
C:/MinGW/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lboost_filesystem-mgw49-mt-1_57
C:/MinGW/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lboost_program_options-mgw49-mt-1_57
C:/MinGW/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lboost_thread-mgw49-mt-1_57
C:/MinGW/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lboost_chrono-mgw49-mt-1_57
C:/MinGW/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -ldb_cxx
C:/MinGW/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lsecp256k1
C:/MinGW/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lgmp
collect2.exe: error: ld returned 1 exit status
makefile.mingw155:167: recipe for target 'Syndicated.exe' failed
mingw32-make: *** [Syndicated.exe] Error 1
please help me fixed it.

**Comment by lvilar** [comment]
Please use latest version with included deps.
