### ISSUE TITLE
Build Windows Cross-Compile w/ Depends

### ISSUE THREAD

**Issue by AmirWaleed** [SyndicateLtd/SyndicateQT#4]
I am trying to build for windows using the standard compile process that bitcoin uses, as well as dash and almost all modern coins.

I am building on linux, and usually, you go to the depends folder, make for the OS, and then compile, but in the /depends/ folder I get a "no make file and no targets specified. Stop" error..

**Comment by lvilar** [comment]
Fixed in v2.0.0
