### ISSUE TITLE
Library not loaded on macOS

### ISSUE THREAD

**Issue by markshep** [SyndicateLtd/SyndicateQT#6]
On my iMac running 10.13.3 (High Sierra) the wallet fails to open.  That's with both the newly released 1.9.9 and the previous version.  Running it from inside Terminal gives the following output:

    dyld: Library not loaded: @loader_path/libboost_system-mt.dylib
      Referenced from: /Applications/000-cryptocoins/Syndicate-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
      Reason: image not found
    Abort trap: 6

The file `Contents/Frameworks/libboost_thread-mt.dylib` does exist in the app so maybe the `@loader_path` bit is wrong and it should be pointing at the app's Frameworks dir instead?  I guess it happens to work on the developers machine because a system-wide version of Boost is installed.

**Comment by markshep** [comment]
Oh, it's loading the bundled `libboost_thread-my.dylib` OK, but then _that's_ trying to load `libboost_system-mt.lib` from the standard path:

    $ otool -L /Applications/000-cryptocoins/Syndicate-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib 
    /Applications/000-cryptocoins/Syndicate-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib:
            @executable_path/../Frameworks/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
            @loader_path/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
            /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
            /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

**Comment by fanpage1** [comment]
I am not expert for database but for me it does not work either. Where can I find some tutorial? Thanks.

**Comment by loafing** [comment]
My Mac wallet won't open  any ideas?

 Check with the developer to make sure Syndicate-Qt works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.

Click Report to see more detailed information and send a report to Apple.

**Comment by lvilar** [comment]
Yes in all cases you are missing the correct boost version. Please use brew to install the missing boost libraries.

**Comment by markshep** [comment]
Surely the correct Boost version should be bundled with the app rather than expecting users to install it?
