### ISSUE TITLE
Windows 10 Wallet sync

### ISSUE THREAD

**Issue by cclabsInc** [SyndicateLtd/SyndicateQT#8]
Created a wallet and transferred coins, but it says out of sync 1 year 42 weeks behind.  It does not appear to be syncing so all of my coins are in limbo.  How does one resolve the syncing issue? 

I checked the debug and network traffic and there is no network traffic. 
I also downloaded the blockchain but I do not see an upload feature.

**Comment by lvilar** [comment]
Please check the port-forwarding or any other network issues.
